// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jnovtwvstcskzbrurgbc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impub3Z0d3ZzdGNza3picnVyZ2JjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MTI4OTIsImV4cCI6MjA2NjQ4ODg5Mn0.bB7OFSYM2RD_f50r4IjRdF9wXz89czY-6Wi9eStPHvc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);